CREATE TABLE UserType (
    id INT PRIMARY KEY IDENTITY(1,1),
    type NVARCHAR(255) NOT NULL
);

CREATE TABLE [User] (
    id INT PRIMARY KEY IDENTITY(1,1),
    email NVARCHAR(255) NOT NULL,
    userTypeId INT NOT NULL FOREIGN KEY REFERENCES UserType(id)
);

CREATE TABLE UserDetail (
    id INT PRIMARY KEY IDENTITY(1,1),
    userId INT NOT NULL FOREIGN KEY REFERENCES [User](id),
    firstName NVARCHAR(255) NOT NULL,
    lastName NVARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    phoneNumber NVARCHAR(15) NOT NULL
);

CREATE TABLE [Order] (
    id INT PRIMARY KEY IDENTITY(1,1),
    customerId INT NOT NULL FOREIGN KEY REFERENCES [User](id),
    staffId INT NOT NULL FOREIGN KEY REFERENCES [User](id),
    dateOfSale DATETIME NOT NULL
);

CREATE TABLE Product (
    id INT PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX),
    price INT NOT NULL
);

CREATE TABLE OrderProduct (
    id INT PRIMARY KEY IDENTITY(1,1),
    orderId INT NOT NULL FOREIGN KEY REFERENCES [Order](id),
    productId INT NOT NULL FOREIGN KEY REFERENCES Product(id),
    PWYL BIT NOT NULL,
    paidAmt INT NOT NULL
);